const AllShows = [
  {
    id: 1,
    title: "Bhajan",
    host: "Sarah Johnson",
    isTrending: true,
    isLive: false,
    timing: "Mondays, 10:00 AM EST",
    duration: "45 minutes",
    rating: 4.8,
    category: "Spiritual",
    description: "Devotional bhajans to bring peace and positivity.",
  },
  {
    id: 2,
    title: "Tamil Music",
    host: "Michael Chen",
    isTrending: true,
    isLive: true,
    timing: "Weekdays, 8:30 AM EST",
    duration: "30 minutes",
    rating: 4.6,
    category: "Music",
    description: "Enjoy the latest and evergreen Tamil hits.",
  },
  {
    id: 3,
    title: "Tamil Classic",
    host: "Dr. Lisa Patel",
    isTrending: false,
    isLive: false,
    timing: "Wednesdays, 2:00 PM EST",
    duration: "60 minutes",
    rating: 4.9,
    category: "Music",
    description: "A journey through timeless Tamil classical melodies.",
  },
  {
    id: 4,
    title: "Hindi Music",
    host: "James Wilson",
    isTrending: true,
    isLive: false,
    timing: "Fridays, 9:00 PM EST",
    duration: "90 minutes",
    rating: 4.7,
    category: "Music",
    description: "Popular Hindi songs from Bollywood and beyond.",
  },
  {
    id: 5,
    title: "English Music",
    host: "Carlo Rossi",
    isTrending: false,
    isLive: true,
    timing: "Saturdays, 12:00 PM EST",
    duration: "45 minutes",
    rating: 4.5,
    category: "Music",
    description: "Hit English tracks across genres from pop to rock.",
  },
//   {
//     id: 6,
//     title: "Bollywood Music",
//     host: "Dr. Robert Kim",
//     isTrending: false,
//     isLive: false,
//     timing: "Tuesdays, 7:00 PM EST",
//     duration: "60 minutes",
//     rating: 4.4,
//     category: "Music",
//     description: "The best of Bollywood’s musical blockbusters.",
//   },
//   {
//     id: 7,
//     title: "Instrumental",
//     host: "Alexandra Martinez",
//     isTrending: true,
//     isLive: true,
//     timing: "Sundays, 11:00 AM EST",
//     duration: "120 minutes",
//     rating: 4.2,
//     category: "Music",
//     description: "Soothing instrumental tunes to relax your mind.",
//   },
//   {
//     id: 8,
//     title: "Party Songs",
//     host: "Emma Thompson",
//     isTrending: false,
//     isLive: false,
//     timing: "Daily, 6:00 AM EST",
//     duration: "20 minutes",
//     rating: 4.9,
//     category: "Music",
//     description: "High-energy tracks to light up your party mood.",
//   },
//   {
//     id: 9,
//     title: "Gaming Hour",
//     host: "Tyler Greene",
//     isTrending: true,
//     isLive: true,
//     timing: "Thursdays, 8:00 PM EST",
//     duration: "60 minutes",
//     rating: 4.7,
//     category: "Gaming",
//     description: "Exciting gaming news, reviews, and live plays.",
//   },
//   {
//     id: 10,
//     title: "Business Insights",
//     host: "Victoria Hughes",
//     isTrending: false,
//     isLive: false,
//     timing: "Mondays, 1:00 PM EST",
//     duration: "45 minutes",
//     rating: 4.5,
//     category: "Business",
//     description: "Expert advice and strategies for business growth.",
//   },
];

export default AllShows;
