const AllShows = [
  {
    id: 1,
    title: "Tech Today",
    host: "Sarah Johnson",
    isTrending: true,
    isLive: false,
    timing: "Mondays, 10:00 AM EST",
    duration: "45 minutes",
    rating: 4.8,
    category: "Technology",
    description: "Latest news and breakthroughs in the tech world",
  },
  {
    id: 2,
    title: "Morning Market Watch",
    host: "Michael Chen",
    isTrending: true,
    isLive: true,
    timing: "Weekdays, 8:30 AM EST",
    duration: "30 minutes",
    rating: 4.6,
    category: "Finance",
    description: "Real-time market analysis and investment tips",
  },
  {
    id: 3,
    title: "Health Matters",
    host: "Dr. Lisa Patel",
    isTrending: false,
    isLive: false,
    timing: "Wednesdays, 2:00 PM EST",
    duration: "60 minutes",
    rating: 4.9,
    category: "Health",
    description:
      "Medical advice and wellness strategies from top healthcare professionals",
  },
  {
    id: 4,
    title: "True Crime Stories",
    host: "James Wilson",
    isTrending: true,
    isLive: false,
    timing: "Fridays, 9:00 PM EST",
    duration: "90 minutes",
    rating: 4.7,
    category: "Crime",
    description: "In-depth investigations of fascinating criminal cases",
  },
  {
    id: 5,
    title: "Cooking with Carlo",
    host: "Carlo Rossi",
    isTrending: false,
    isLive: true,
    timing: "Saturdays, 12:00 PM EST",
    duration: "45 minutes",
    rating: 4.5,
    category: "Food",
    description: "Gourmet cooking demonstrations with celebrity chef Carlo",
  },
  {
    id: 6,
    title: "Science Unveiled",
    host: "Dr. Robert Kim",
    isTrending: false,
    isLive: false,
    timing: "Tuesdays, 7:00 PM EST",
    duration: "60 minutes",
    rating: 4.4,
    category: "Science",
    description:
      "Exploring the mysteries of the universe and recent scientific discoveries",
  },
  {
    id: 7,
    title: "Political Roundtable",
    host: "Alexandra Martinez",
    isTrending: true,
    isLive: true,
    timing: "Sundays, 11:00 AM EST",
    duration: "120 minutes",
    rating: 4.2,
    category: "Politics",
    description:
      "Lively debates on current political events with expert analysts",
  },
  {
    id: 8,
    title: "Mindful Meditation",
    host: "Emma Thompson",
    isTrending: false,
    isLive: false,
    timing: "Daily, 6:00 AM EST",
    duration: "20 minutes",
    rating: 4.9,
    category: "Wellness",
    description:
      "Guided meditation sessions for stress relief and mental clarity",
  },
  {
    id: 9,
    title: "Gaming Hour",
    host: "Tyler Greene",
    isTrending: true,
    isLive: true,
    timing: "Thursdays, 8:00 PM EST",
    duration: "60 minutes",
    rating: 4.7,
    category: "Gaming",
    description:
      "Latest gaming news, reviews, and live gameplay with audience interaction",
  },
  {
    id: 10,
    title: "Business Insights",
    host: "Victoria Hughes",
    isTrending: false,
    isLive: false,
    timing: "Mondays, 1:00 PM EST",
    duration: "45 minutes",
    rating: 4.5,
    category: "Business",
    description:
      "Strategies and advice from successful entrepreneurs and business leaders",
  },
];
export default AllShows;
